// src/data/especialidades.js

// Lista fixa com TODAS as especialidades médicas
export const especialidades = [
  { id: 1, nome: "Clinica Médica", cadastros: 0 },
  { id: 2, nome: "Pediatria", cadastros: 0 },
  { id: 3, nome: "Ginecologia e Obstetrícia", cadastros: 0 },
  { id: 4, nome: "Cardiologia", cadastros: 0 },
  { id: 5, nome: "Ortopedia e Traumatologia", cadastros: 0 },
  { id: 6, nome: "Dermatologia", cadastros: 0 },
  { id: 7, nome: "Psiquiatria", cadastros: 0 },
  { id: 8, nome: "Oftalmologia", cadastros: 0 },
  { id: 9, nome: "Otorrinolaringologia", cadastros: 0 },
  { id: 10, nome: "Urologia", cadastros: 0 },
  { id: 11, nome: "Anestesiologia", cadastros: 0 },
  { id: 12, nome: "Radiologia e Diagnóstico por Imagem", cadastros: 0 },
  { id: 13, nome: "Endocrinologia e Metabologia", cadastros: 0 },
  { id: 14, nome: "Gastroenterologia", cadastros: 0 },
  { id: 15, nome: "Genética Médica", cadastros: 0 },
  { id: 16, nome: "Geriatria", cadastros: 0 },
  { id: 17, nome: "Hematologia e Hemoterapia", cadastros: 0 },
  { id: 18, nome: "Homeopatia", cadastros: 0 },
  { id: 19, nome: "Infectologia", cadastros: 0 },
  { id: 20, nome: "Mastologia", cadastros: 0 },
  { id: 21, nome: "Medicina de Emergência", cadastros: 0 },
  { id: 22, nome: "Medicina de Família e Comunidade", cadastros: 0 },
  { id: 23, nome: "Medicina do Trabalho", cadastros: 0 },
  { id: 24, nome: "Medicina Esportiva", cadastros: 0 },
  { id: 25, nome: "Medicina Física e Reabilitação", cadastros: 0 },
  { id: 26, nome: "Medicina Intensiva", cadastros: 0 },
  { id: 27, nome: "Medicina Legal e Perícia Médica", cadastros: 0 },
  { id: 28, nome: "Medicina Nuclear", cadastros: 0 },
  { id: 29, nome: "Medicina Preventiva e Social", cadastros: 0 },
  { id: 30, nome: "Nefrologia", cadastros: 0 },
  { id: 31, nome: "Neurologia", cadastros: 0 },
  { id: 32, nome: "Neurocirurgia", cadastros: 0 },
  { id: 33, nome: "Nutrologia", cadastros: 0 },
  { id: 34, nome: "Oncologia Clínica", cadastros: 0 },
  { id: 35, nome: "Patologia", cadastros: 0 },
  { id: 36, nome: "Patologia Clínica/Medicina Laboratorial", cadastros: 0 },
  { id: 37, nome: "Pneumologia", cadastros: 0 },
  { id: 38, nome: "Radioterapia", cadastros: 0 },
  { id: 39, nome: "Reumatologia", cadastros: 0 },
  { id: 40, nome: "Acupuntura", cadastros: 0 },
  { id: 41, nome: "Dor", cadastros: 0 },
  { id: 42, nome: "Cirurgia Geral", cadastros: 0 },
  { id: 43, nome: "Cirurgia Plástica", cadastros: 0 },
  { id: 44, nome: "Cirurgia Vascular", cadastros: 0 },
  { id: 45, nome: "Cirurgia Pediátrica", cadastros: 0 },
  { id: 46, nome: "Cirurgia Cardiovascular", cadastros: 0 },
  { id: 47, nome: "Cirurgia Bucomaxilofacial", cadastros: 0 },
  { id: 48, nome: "Cirurgia Torácica", cadastros: 0 },
  { id: 49, nome: "Coloproctologia", cadastros: 0 },
  { id: 50, nome: "Cirurgia de Cabeça e Pescoço", cadastros: 0 },
  { id: 51, nome: "Cirurgia do Aparelho Digestivo", cadastros: 0 },
  { id: 52, nome: "Cardiologia Intervencionista", cadastros: 0 },
  { id: 53, nome: "Cardiologia Pediátrica", cadastros: 0 },
  { id: 54, nome: "Dermatopatologia", cadastros: 0 },
  { id: 55, nome: "Endocrinologia Pediátrica", cadastros: 0 },
  { id: 56, nome: "Gastroenterologia Pediátrica", cadastros: 0 },
  { id: 57, nome: "Hematologia Pediátrica", cadastros: 0 },
  { id: 58, nome: "Infectologia Pediátrica", cadastros: 0 },
  { id: 59, nome: "Nefrologia Pediátrica", cadastros: 0 },
  { id: 60, nome: "Neurologia Pediátrica", cadastros: 0 },
  { id: 61, nome: "Oncologia Pediátrica", cadastros: 0 },
  { id: 62, nome: "Pneumologia Pediátrica", cadastros: 0 },
  { id: 63, nome: "Reumatologia Pediátrica", cadastros: 0 },
  { id: 64, nome: "Cirurgia Cardiovascular Pediátrica", cadastros: 0 },
  { id: 65, nome: "Cirurgia Pediátrica", cadastros: 0 },
  { id: 66, nome: "Cirurgia Torácica Pediátrica", cadastros: 0 },
  { id: 67, nome: "Cirurgia Vascular Pediátrica", cadastros: 0 },
  { id: 68, nome: "Cirurgia Oncológica Pediátrica", cadastros: 0 },
  { id: 69, nome: "Medicina de Cuidados Paliativos", cadastros: 0 },
  { id: 70, nome: "Medicina do Sono", cadastros: 0 },
  { id: 71, nome: "Medicina Integrativa", cadastros: 0 },
  { id: 72, nome: "Medicina Aeroespacial", cadastros: 0 },
  { id: 73, nome: "Medicina de Viagem", cadastros: 0 },
  { id: 74, nome: "Medicina de Desastres", cadastros: 0 },
  { id: 75, nome: "Medicina de Saúde Pública", cadastros: 0 },
  { id: 76, nome:"Clinico", cadastros: 0},
];

// Função para ordenar as especialidades pela quantidade de cadastros
export function ordenarEspecialidades(lista) {
  return [...lista].sort(
    (a, b) => b.cadastros - a.cadastros || a.nome.localeCompare(b.nome)
  );
}
