// src/data/medicosData.js
const medicos = [
  { id: 1, nome: "DR. ALEXANDRE MAURICIO RODRIGUES DE ARAUJO", especialidade: "", crm: "", observacao: "" },
  { id: 2, nome: "DR. ALVARO ALEJANDRO", especialidade: "", crm: "", observacao: "" },
  { id: 3, nome: "DR. ANDERSON CARLOS BERNAL DA SILVA", especialidade: "", crm: "", observacao: "" },
  { id: 4, nome: "DR. ANDERSON LUIS PLAZA", especialidade: "", crm: "", observacao: "" },
  { id: 5, nome: "DR. ANDRE ALVES DE OLIVEIRA", especialidade: "", crm: "", observacao: "" },
  { id: 6, nome: "DR. ANDREY LUIS MAUA TIMOTEO", especialidade: "", crm: "", observacao: "" },
  { id: 7, nome: "DR. ANIBAL DIAZ", especialidade: "", crm: "", observacao: "" },
  { id: 8, nome: "DR. ANTHONY LUCAS ALENCAR DE OLIVEIRA", especialidade: "", crm: "", observacao: "" },
  { id: 9, nome: "DR. ARTHUR VITOR DE CARVALHO", especialidade: "", crm: "", observacao: "" },
  { id: 10, nome: "DR. BRADO PLAZA", especialidade: "", crm: "", observacao: "" },
  { id: 11, nome: "DR. BRANDON LUIS PLAZA VELASQUEZ", especialidade: "", crm: "", observacao: "" },
  { id: 12, nome: "DR. BRUNO EZEQUIEL PAIVA DA FONSECA", especialidade: "", crm: "", observacao: "" },
  { id: 13, nome: "DR. BRUNO SERGIO GARCIA SIMOES", especialidade: "", crm: "", observacao: "" },
  { id: 14, nome: "DR. CARLOS HUMBERTO VIDAL FLORES", especialidade: "", crm: "", observacao: "" },
  { id: 15, nome: "DR. CARLOS ROBERTO REIS", especialidade: "", crm: "", observacao: "" },
  { id: 16, nome: "DR. NATHANAEL ROGER DE SOUZA", especialidade: "", crm: "", observacao: "" },
  { id: 17, nome: "DR. CASSIO ANTONIO DE SOUZA", especialidade: "", crm: "", observacao: "" },
  { id: 18, nome: "DR. CELIO ROBERTO DE CARVALHO SILVA", especialidade: "", crm: "", observacao: "" },
  { id: 19, nome: "DR. CELIUS FABRICIO DE AZEVEDO", especialidade: "", crm: "", observacao: "" },
  { id: 20, nome: "DR. CELSO CARLOS GUIMARAES FILHO", especialidade: "", crm: "", observacao: "" },
  { id: 21, nome: "DR. CLAUBER SANTANA FLORES", especialidade: "", crm: "", observacao: "" },
  { id: 22, nome: "DR. DANIEL EPIFANIO RIOS ARIZA", especialidade: "", crm: "", observacao: "" },
  { id: 23, nome: "DR. DANIEL JOSE HONG", especialidade: "", crm: "", observacao: "" },
  { id: 24, nome: "DR. DARCIO PINTO DA FONSECA", especialidade: "", crm: "", observacao: "" },
  { id: 25, nome: "DR. DARIO MOREIRA ANTONIA", especialidade: "", crm: "", observacao: "" },
  { id: 26, nome: "DR. DAVID BRAGA BARBOSA RIBEIRO", especialidade: "", crm: "", observacao: "" },
  { id: 27, nome: "DR. DAVID PEREIRA PARANAYBA", especialidade: "", crm: "", observacao: "" },
  { id: 28, nome: "DR. DAVID TANG CHANG", especialidade: "", crm: "", observacao: "" },
  { id: 29, nome: "DR. DENNIS CAMACHO LIVA", especialidade: "", crm: "", observacao: "" },
  { id: 30, nome: "DR. DIEGO DE SOUZA INACIO", especialidade: "", crm: "", observacao: "" },
  { id: 31, nome: "DR. DIEGO FOLETTO", especialidade: "", crm: "", observacao: "" },
  { id: 32, nome: "DR. DIEGO NUNES BEZERRA", especialidade: "", crm: "", observacao: "" },
  { id: 33, nome: "DR. DIOGO AGUIAR DE ALMEIDA", especialidade: "", crm: "", observacao: "" },
  { id: 34, nome: "DR. EDER LUCAS SANTOS TIAGO", especialidade: "", crm: "", observacao: "" },
  { id: 35, nome: "DR. EDER SILVA GUEDES", especialidade: "", crm: "", observacao: "" },
  { id: 36, nome: "DR. EDGAR PRADO ALVES", especialidade: "", crm: "", observacao: "" },
  { id: 37, nome: "DR. EDSON DONEZETE SOARES", especialidade: "", crm: "", observacao: "" },
  { id: 38, nome: "DR. EDUARDO CUSATIS NOVAES", especialidade: "", crm: "", observacao: "" },
  { id: 39, nome: "DR. EDUARDO LEITE VERRI FERREIRA", especialidade: "", crm: "", observacao: "" },
  { id: 40, nome: "DR. EDUARDO MEYER MORYTZ MOREIRA LIMA", especialidade: "", crm: "", observacao: "" },
  // ... Continue a sequência até o último médico
];

export default medicos;
